server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/obschepit
    username: postgres
    password: virusvirus21rus
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    database: postgresql
    hibernate:
      ddl-auto: update